# pytest.ini
[pytest]

# Ensure root is added to Python path
pythonpath = .

# Global options
addopts = 
    -v
    -s
    --clean-alluredir
    --alluredir=reports/allure-results
    --reruns 2
    --reruns-delay 2

# Test file discovery rules
python_files = 
    tests/**/*.py
    test_*.py
    *_tests.py

# Test markers
markers =
    web: Web UI tests using Playwright
    api: API tests
    bdd: BDD scenarios
    regression: Regression suite

# Pytest-BDD configuration
bdd_features_base_dir = tests/web/features
bdd_strict = true
