#config/config.yaml
base_url: "https://www.altimetrik.com/"
env: "staging"

browser: chromium       # chromium / firefox / webkit
headed: true            # false = headless

screenshot_on_failure: true
retry_count: 2

browser_args:
  - "--start-maximized"